### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by muarachmann** [whitecube/laravel-prices#3]
I get this error when using the package.
```
Uncaught ParseError: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in ...vendor/whitecube/laravel-prices/src/HasPrices.php:40 Stack
```

https://github.com/whitecube/laravel-prices/blob/dfec677efa45339cf0bb20d4a9524fe62d25cbcc/src/HasPrices.php#L40

**Comment by toonvandenbos** [comment]
Hi @muarachmann,

`?->` is the nullsafe operator, available from PHP 8.0. I guess you should upgrade your PHP version if you want to use this package. :-)
